const name_adj = [ 'Mad',
  'Master',
  'Dynamic',
  'E-ratic',
  'Wacko',
  'Fearless',
  'Misunderstood',
  'Quiet',
  'Pesty',
  'Gentlemen',
  'Profound',
  'Respected',
  'Amateur',
  'Shriekin’',
  'Lucky',
  'Phantom',
  'Smilin’',
  'Thunderous',
  'Tuff',
  'Scratchin’',
  'Drunken',
  'X-cessive',
  'X-pert',
  'Zexy',
  'Ruff',
  'Intellectual',
  'Unlucky',
  'Vizual',
  'Foolish',
  'Midnight',
  'Mighty',
  'Violent',
  'Vulgar',
  'Crazy',
  'Annoyin’',
  'Arrogant',
  'B-loved',
  'Wicked',
  'Lazy-assed',
  'Childish' ];

function findNameAdj(ind) {
    return name_adj[ind];
}

module.exports = { findNameAdj, adjlen: name_adj.length };